# Cardano Node
cardano:
  node:
    host: delta.relay.easy1staking.com
    socatPort: 30100

ogmios.url: ws://delta.relay.easy1staking.com:31337

wallet:
  mnemonic: ""

blockfrost:
  key: mainnetKWaNkQcrF1erC3u3SZjaFxZiM2M20jFM

swap:
  transaction:
    submitTo: local